import { Link } from "react-router";
import {
  FiArrowLeft,
  FiCode,
  FiLayers,
  FiCheckSquare,
  FiCpu,
  FiZap,
  FiBookOpen,
  FiHome,
  FiTerminal,
} from "react-icons/fi";
import { PHASE_META } from "../App";
import { useTheme } from "../context/ThemeContext";
import { ThemeProvider } from "../context/ThemeContext";
import "../themes.css";

/* ── icon map ─────────────────────────────────────────────────────── */
const ICONS = {
  blue:   <FiCode   className="w-4 h-4" />,
  purple: <FiLayers className="w-4 h-4" />,
  green:  <FiCheckSquare className="w-4 h-4" />,
  amber:  <FiCpu    className="w-4 h-4" />,
  orange: <FiZap    className="w-4 h-4" />,
  red:    <FiTerminal className="w-4 h-4" />,
};

/* ── extended details per phase ──────────────────────────────────── */
const DETAILS = {
  blue:
    "Implementation: typically a hand-written or generated DFA (via tools like flex/lex). Input: character stream. Output: token stream. Errors: invalid characters, malformed literals.",
  purple:
    "Implementation: recursive-descent, LL(k), or LALR(1) parser (e.g. generated by yacc/bison). Input: token stream. Output: AST. Errors: syntax errors — missing operators, unbalanced brackets.",
  green:
    "Implementation: tree-walk visitor pattern over the AST. Builds a multi-level symbol table (scope stack). Input: AST. Output: annotated AST + symbol table. Errors: type mismatch, undeclared identifier, redeclaration.",
  amber:
    "Implementation: AST post-order traversal generating TAC instructions. Each binary node → one TAC instruction with a fresh temp. Input: annotated AST. Output: TAC list. Memory layout: temps are virtual registers spilled later.",
  orange:
    "Key optimisations implemented here: (1) Constant folding — replace (3+4) with 7 at compile time. (2) Copy propagation — replace t = x; y = t with y = x. (3) Dead-code elimination — drop instructions whose result is never read. (4) CSE — cache common sub-expressions in a temp.",
  red:
    "Tasks: instruction selection (pattern matching TAC to opcode), register allocation (graph colouring or linear scan), calling convention adherence (push/pop, stack frame). Output: assembly text. Further processed by assembler → object file → linker → executable.",
};

const HowItWorksInner = () => {
  const { theme } = useTheme();

  return (
    <div className="hiw-root" data-theme={theme}>
      {/* ── Topbar ── */}
      <header className="topbar">
        <div className="topbar__inner">
          <Link to="/" className="brand">
            <div className="brand__logo-slot">
              <img
                src=""
                alt=""
                className="brand__logo-img"
                onError={(e) => {
                  e.currentTarget.style.display = "none";
                  e.currentTarget.nextElementSibling.style.display = "flex";
                }}
              />
              <div className="brand__logo-fallback">
                <FiTerminal className="w-5 h-5" />
              </div>
            </div>
            <div className="brand__text">
              <span className="brand__title">Compiler Visualizer</span>
              <span className="brand__sub">// Compiler Phases Guide</span>
            </div>
          </Link>

          <nav className="topbar__nav">
            <Link to="/" className="nav-pill">
              <FiHome className="w-3.5 h-3.5" />
              <span>Visualiser</span>
            </Link>
            <Link to="/" className="nav-pill">
              <FiArrowLeft className="w-3.5 h-3.5" />
              <span>Back</span>
            </Link>
          </nav>
        </div>
      </header>

      <div className="hiw-main">
        {/* ── Hero ── */}
        <div className="hiw-hero">
          <h2>
            The Six Phases of{" "}
            <span
              style={{
                background: "linear-gradient(90deg, var(--accent), var(--accent2))",
                WebkitBackgroundClip: "text",
                WebkitTextFillColor: "transparent",
                backgroundClip: "text",
              }}
            >
              Compilation
            </span>
          </h2>
          <p>
            A compiler transforms human-readable source code into
            machine-executable binary through a structured pipeline. Each phase
            has a well-defined input, output, and responsibility.
          </p>
        </div>

        {/* ── Phase cards ── */}
        <div className="hiw-grid">
          {PHASE_META.map((phase) => (
            <div key={phase.id} className="hiw-card">
              <div className="hiw-card__head">
                <div className={`hiw-card__num col-${phase.colorKey}`}>
                  {ICONS[phase.colorKey]}
                </div>
                <div>
                  <div className="hiw-card__title">{phase.title}</div>
                  <div className="hiw-card__tagline">{phase.tagline}</div>
                </div>
              </div>
              <p className="hiw-card__desc">{phase.explanation}</p>
              <p className="hiw-card__detail">
                {DETAILS[phase.colorKey]}
              </p>
            </div>
          ))}
        </div>

        {/* ── About card ── */}
        <div className="about-card">
          <h3>
            <FiBookOpen className="w-5 h-5" style={{ color: "var(--accent)" }} />
            About This Tool
          </h3>
          <p>
            This Compiler Phase Visualiser helps students and practitioners
            understand how source code is transformed through each stage of
            compilation. Enter any arithmetic expression and watch it flow
            through all six phases — with the output of every stage rendered
            interactively.
          </p>
          <p>
            The analysis runs in the browser using a hand-written recursive-descent
            parser, a TAC generator, a copy-propagation optimiser, and an
            x86-like code generator — no server round-trip required. An optional
            AI-powered backend (via Groq) can provide richer analysis when a
            VITE_GROQ_API_KEY is set.
          </p>
        </div>

        {/* ── Back link ── */}
        <div style={{ textAlign: "center" }}>
          <Link to="/" className="guide-cta">
            <FiHome className="w-4 h-4" />
            Try the Visualiser
          </Link>
        </div>
      </div>
    </div>
  );
};

/* Wrap in ThemeProvider in case it renders standalone */
const HowItWorks = () => (
  <ThemeProvider>
    <HowItWorksInner />
  </ThemeProvider>
);

export default HowItWorks;
